// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIWa0EQuOSKEGyd5giMiYPr_2EMLHTrkU',
    appId: '1:646820899036:web:c41d6abbfa6f641ca9ac19',
    messagingSenderId: '646820899036',
    projectId: 'oktay-6beab',
    authDomain: 'oktay-6beab.firebaseapp.com',
    databaseURL: 'https://oktay-6beab-default-rtdb.firebaseio.com',
    storageBucket: 'oktay-6beab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4VXoEMQQYVfSt61aFnW0mhB5GFogRIFg',
    appId: '1:646820899036:android:5bc2239698d6a516a9ac19',
    messagingSenderId: '646820899036',
    projectId: 'oktay-6beab',
    databaseURL: 'https://oktay-6beab-default-rtdb.firebaseio.com',
    storageBucket: 'oktay-6beab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwBWVfxSCgr7NDGgwda5MzIJAFFWgPUPI',
    appId: '1:646820899036:ios:022da951aa5ac38ca9ac19',
    messagingSenderId: '646820899036',
    projectId: 'oktay-6beab',
    databaseURL: 'https://oktay-6beab-default-rtdb.firebaseio.com',
    storageBucket: 'oktay-6beab.appspot.com',
    iosClientId: '646820899036-kjc62gj2219977e0ee387r09khl7i0vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.oktay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwBWVfxSCgr7NDGgwda5MzIJAFFWgPUPI',
    appId: '1:646820899036:ios:022da951aa5ac38ca9ac19',
    messagingSenderId: '646820899036',
    projectId: 'oktay-6beab',
    databaseURL: 'https://oktay-6beab-default-rtdb.firebaseio.com',
    storageBucket: 'oktay-6beab.appspot.com',
    iosClientId: '646820899036-kjc62gj2219977e0ee387r09khl7i0vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.oktay',
  );
}
